language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get upgrade -qq"
# command to install dependencies
install: 
  - "sudo pip install nose"
# command to run tests
script: nosetests
